package runner

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/darkLord19/foglet/internal/ghcli"
	"github.com/darkLord19/foglet/internal/proc"
)

func (r *Runner) commitSessionChanges(ctx context.Context, toolName, workdir, prompt, commitMsg string) (sha, finalMsg string, changed bool, err error) {
	statusOut, err := proc.Run(ctx, workdir, "git", "status", "--porcelain")
	if err != nil {
		return "", "", false, fmt.Errorf("git status failed: %w", withOutput(err, statusOut))
	}
	if len(statusOut) == 0 {
		return "", "", false, nil
	}

	if output, err := proc.Run(ctx, workdir, "git", "add", "."); err != nil {
		return "", "", false, fmt.Errorf("git add failed: %w", withOutput(err, output))
	}

	finalMsg = strings.TrimSpace(commitMsg)
	if finalMsg == "" {
		generated, err := r.generateCommitMessage(ctx, toolName, workdir, prompt)
		if isCanceledError(err) {
			return "", "", false, err
		}
		if err != nil || strings.TrimSpace(generated) == "" {
			finalMsg = fallbackCommitMessage(prompt)
		} else {
			finalMsg = generated
		}
	}

	if output, err := proc.Run(ctx, workdir, "git", "commit", "-m", finalMsg); err != nil {
		return "", "", false, fmt.Errorf("git commit failed: %w", withOutput(err, output))
	}

	shaOut, err := proc.Run(ctx, workdir, "git", "rev-parse", "HEAD")
	if err != nil {
		return "", "", false, fmt.Errorf("git rev-parse failed: %w", withOutput(err, shaOut))
	}

	return strings.TrimSpace(string(shaOut)), finalMsg, true, nil
}

func (r *Runner) pushBranch(ctx context.Context, workdir, branch string, setUpstream bool) error {
	args := []string{"push", "origin", branch}
	if setUpstream {
		args = []string{"push", "-u", "origin", branch}
	}
	output, err := proc.Run(ctx, workdir, "git", args...)
	if err != nil {
		return fmt.Errorf("git %s failed: %w", strings.Join(args, " "), withOutput(err, output))
	}
	return nil
}

func (r *Runner) createDraftPR(ctx context.Context, workdir, baseBranch, branch, prompt, tool, sessionID, customTitle string) (string, error) {
	if !ghcli.IsGhAvailable() {
		return "", fmt.Errorf("gh CLI not available")
	}
	title := resolvePRTitle(customTitle, prompt)
	body := fmt.Sprintf("Generated by Fog session\n\nSession ID: %s\nAI Tool: %s\n\nPrompt:\n%s",
		sessionID,
		tool,
		strings.TrimSpace(prompt),
	)

	return ghcli.CreatePRWithContext(ctx, workdir, title, body, baseBranch, branch, true)
}

func withOutput(err error, output []byte) error {
	if err == nil {
		return nil
	}
	text := strings.TrimSpace(string(output))
	if text == "" {
		return err
	}
	return fmt.Errorf("%w\n%s", err, text)
}

func isCanceledError(err error) bool {
	return errors.Is(err, proc.ErrCanceled) || errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded)
}

var nonWorktreeNameChar = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

func runWorktreeName(branch, runID string) string {
	branch = nonWorktreeNameChar.ReplaceAllString(strings.TrimSpace(branch), "-")
	branch = strings.Trim(branch, "-._")
	if branch == "" {
		branch = "run"
	}
	if len(branch) > 180 {
		branch = branch[:180]
		branch = strings.Trim(branch, "-._")
		if branch == "" {
			branch = "run"
		}
	}
	suffix := strings.TrimSpace(runID)
	if len(suffix) > 8 {
		suffix = suffix[:8]
	}
	suffix = nonWorktreeNameChar.ReplaceAllString(suffix, "")
	if suffix == "" {
		suffix = "latest"
	}
	return branch + "-" + suffix
}

func fallbackCommitMessage(prompt string) string {
	base := strings.TrimSpace(prompt)
	if base == "" {
		base = "update code"
	}
	return fmt.Sprintf("feat: %s\n\nGenerated by Fog session", truncate(base, 120))
}
