package runner

import (
	"strings"
	"testing"
	"time"

	"github.com/darkLord19/foglet/internal/state"
)

func TestStartSessionRequiresStateStore(t *testing.T) {
	r, err := New(t.TempDir(), t.TempDir(), nil)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	_, _, err = r.StartSession(StartSessionOptions{
		RepoName: "acme/api",
		RepoPath: t.TempDir(),
		Branch:   "fog/test",
		Tool:     "claude",
		Prompt:   "test",
	})
	if err == nil {
		t.Fatal("expected error when state store is missing")
	}
}

func TestStartSessionValidatesRequiredFields(t *testing.T) {
	st, err := state.NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("new state store failed: %v", err)
	}
	defer func() { _ = st.Close() }()

	r, err := New(t.TempDir(), t.TempDir(), st)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	_, _, err = r.StartSession(StartSessionOptions{
		RepoName: "acme/api",
		RepoPath: t.TempDir(),
		Branch:   "",
		Tool:     "claude",
		Prompt:   "test",
	})
	if err == nil || !strings.Contains(err.Error(), "branch is required") {
		t.Fatalf("expected branch validation error, got: %v", err)
	}
}

func TestContinueSessionRejectsBusySession(t *testing.T) {
	st, err := state.NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("new state store failed: %v", err)
	}
	defer func() { _ = st.Close() }()

	r, err := New(t.TempDir(), t.TempDir(), st)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	if _, err := st.UpsertRepo(state.Repo{
		Name:             "acme/api",
		URL:              "https://github.com/acme/api.git",
		Host:             "github.com",
		Owner:            "acme",
		Repo:             "api",
		BarePath:         "/tmp/acme-api/repo.git",
		BaseWorktreePath: "/tmp/acme-api/base",
		DefaultBranch:    "main",
	}); err != nil {
		t.Fatalf("upsert repo failed: %v", err)
	}

	if err := st.CreateSession(state.Session{
		ID:           "session-1",
		RepoName:     "acme/api",
		Branch:       "fog/test",
		WorktreePath: "/tmp/worktree",
		Tool:         "claude",
		AutoPR:       false,
		Status:       "AI_RUNNING",
		Busy:         true,
		CreatedAt:    time.Now().UTC(),
		UpdatedAt:    time.Now().UTC(),
	}); err != nil {
		t.Fatalf("create session failed: %v", err)
	}

	_, err = r.ContinueSession("session-1", "follow up")
	if err == nil || !strings.Contains(err.Error(), "is busy") {
		t.Fatalf("expected busy session error, got %v", err)
	}
}

func TestPrepareFollowUpRunReusesSessionWorktree(t *testing.T) {
	st, err := state.NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("new state store failed: %v", err)
	}
	defer func() { _ = st.Close() }()

	r, err := New(t.TempDir(), t.TempDir(), st)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	if _, err := st.UpsertRepo(state.Repo{
		Name:             "acme/api",
		URL:              "https://github.com/acme/api.git",
		Host:             "github.com",
		Owner:            "acme",
		Repo:             "api",
		BarePath:         "/tmp/acme-api/repo.git",
		BaseWorktreePath: "/tmp/acme-api/base",
		DefaultBranch:    "main",
	}); err != nil {
		t.Fatalf("upsert repo failed: %v", err)
	}

	worktreePath := "/tmp/acme-api/worktrees/fog-branch"
	now := time.Now().UTC()
	if err := st.CreateSession(state.Session{
		ID:           "session-1",
		RepoName:     "acme/api",
		Branch:       "fog/branch",
		WorktreePath: worktreePath,
		Tool:         "claude",
		AutoPR:       false,
		Status:       "COMPLETED",
		Busy:         false,
		CreatedAt:    now,
		UpdatedAt:    now,
	}); err != nil {
		t.Fatalf("create session failed: %v", err)
	}

	_, run, _, err := r.prepareFollowUpRun("session-1", "follow up")
	if err != nil {
		t.Fatalf("prepareFollowUpRun failed: %v", err)
	}
	if run.WorktreePath != worktreePath {
		t.Fatalf("follow-up run should reuse session worktree: got %q want %q", run.WorktreePath, worktreePath)
	}
}

func TestTruncate(t *testing.T) {
	got := truncate("abcdefgh", 4)
	if got != "abcd..." {
		t.Fatalf("unexpected truncate output: %q", got)
	}
}

func TestNormalizeCommitMessageStripsCodeFence(t *testing.T) {
	raw := "```git\nfeat: add otp login\n\nInclude tests\n```"
	got := normalizeCommitMessage(raw)
	if got != "feat: add otp login\n\nInclude tests" {
		t.Fatalf("unexpected normalized commit message: %q", got)
	}
}

func TestFallbackCommitMessage(t *testing.T) {
	got := fallbackCommitMessage("add login endpoint")
	if !strings.HasPrefix(got, "feat: add login endpoint") {
		t.Fatalf("unexpected fallback commit message: %q", got)
	}
	if !strings.Contains(got, "Generated by Fog session") {
		t.Fatalf("expected footer in fallback commit message: %q", got)
	}
}

func TestRunWorktreeName(t *testing.T) {
	got := runWorktreeName("team/add otp!!", "1234567890abcdef")
	if !strings.HasPrefix(got, "team-add-otp-12345678") {
		t.Fatalf("unexpected worktree name: %q", got)
	}
	if strings.Contains(got, "/") || strings.Contains(got, " ") {
		t.Fatalf("worktree name should be sanitized: %q", got)
	}
}

func TestCancelSessionLatestRunCancelsActiveLatestRun(t *testing.T) {
	st, err := state.NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("new state store failed: %v", err)
	}
	defer func() { _ = st.Close() }()

	r, err := New(t.TempDir(), t.TempDir(), st)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	if _, err := st.UpsertRepo(state.Repo{
		Name:             "acme/api",
		URL:              "https://github.com/acme/api.git",
		Host:             "github.com",
		Owner:            "acme",
		Repo:             "api",
		BarePath:         "/tmp/acme-api/repo.git",
		BaseWorktreePath: "/tmp/acme-api/base",
		DefaultBranch:    "main",
	}); err != nil {
		t.Fatalf("upsert repo failed: %v", err)
	}

	now := time.Now().UTC()
	if err := st.CreateSession(state.Session{
		ID:           "session-1",
		RepoName:     "acme/api",
		Branch:       "fog/test",
		WorktreePath: "/tmp/worktree",
		Tool:         "claude",
		Status:       "AI_RUNNING",
		Busy:         true,
		CreatedAt:    now,
		UpdatedAt:    now,
	}); err != nil {
		t.Fatalf("create session failed: %v", err)
	}
	if err := st.CreateRun(state.Run{
		ID:           "run-1",
		SessionID:    "session-1",
		Prompt:       "do work",
		WorktreePath: "/tmp/worktree",
		State:        "AI_RUNNING",
		CreatedAt:    now,
		UpdatedAt:    now,
	}); err != nil {
		t.Fatalf("create run failed: %v", err)
	}

	called := false
	r.active["session-1"] = &activeRun{
		sessionID: "session-1",
		runID:     "run-1",
		cancel: func() {
			called = true
		},
	}

	run, err := r.CancelSessionLatestRun("session-1")
	if err != nil {
		t.Fatalf("cancel session failed: %v", err)
	}
	if run.ID != "run-1" {
		t.Fatalf("unexpected run id: %q", run.ID)
	}
	if !called {
		t.Fatal("expected cancel function to be called")
	}
}

func TestLookupConversationIDFindsLatestPriorRunSessionID(t *testing.T) {
	st, err := state.NewStore(t.TempDir())
	if err != nil {
		t.Fatalf("new state store failed: %v", err)
	}
	defer func() { _ = st.Close() }()

	r, err := New(t.TempDir(), t.TempDir(), st)
	if err != nil {
		t.Fatalf("new runner failed: %v", err)
	}

	if _, err := st.UpsertRepo(state.Repo{
		Name:             "acme/api",
		URL:              "https://github.com/acme/api.git",
		Host:             "github.com",
		Owner:            "acme",
		Repo:             "api",
		BarePath:         "/tmp/acme-api/repo.git",
		BaseWorktreePath: "/tmp/acme-api/base",
		DefaultBranch:    "main",
	}); err != nil {
		t.Fatalf("upsert repo failed: %v", err)
	}

	now := time.Now().UTC()
	if err := st.CreateSession(state.Session{
		ID:           "session-1",
		RepoName:     "acme/api",
		Branch:       "fog/test",
		WorktreePath: "/tmp/worktree",
		Tool:         "claude",
		Status:       "COMPLETED",
		Busy:         false,
		CreatedAt:    now,
		UpdatedAt:    now,
	}); err != nil {
		t.Fatalf("create session failed: %v", err)
	}

	if err := st.CreateRun(state.Run{
		ID:           "run-1",
		SessionID:    "session-1",
		Prompt:       "first run",
		WorktreePath: "/tmp/worktree",
		State:        "COMPLETED",
		CreatedAt:    now.Add(-2 * time.Minute),
		UpdatedAt:    now.Add(-2 * time.Minute),
	}); err != nil {
		t.Fatalf("create run-1 failed: %v", err)
	}
	if err := st.AppendRunEvent(state.RunEvent{
		RunID: "run-1",
		Type:  "ai_session",
		Data:  "session-token-1",
		TS:    now.Add(-2 * time.Minute),
	}); err != nil {
		t.Fatalf("append run-1 event failed: %v", err)
	}

	if err := st.CreateRun(state.Run{
		ID:           "run-2",
		SessionID:    "session-1",
		Prompt:       "second run",
		WorktreePath: "/tmp/worktree",
		State:        "CREATED",
		CreatedAt:    now.Add(-1 * time.Minute),
		UpdatedAt:    now.Add(-1 * time.Minute),
	}); err != nil {
		t.Fatalf("create run-2 failed: %v", err)
	}

	got := r.lookupConversationID("session-1", "run-2")
	if got != "session-token-1" {
		t.Fatalf("unexpected conversation id: got %q want %q", got, "session-token-1")
	}
}

func TestExtractCommitMessage(t *testing.T) {
	tests := []struct {
		name     string
		output   string
		expected string
	}{
		{
			name:     "Full format",
			output:   "The changes have been made.\n<commit_message>feat: add something</commit_message>\nHope this helps!",
			expected: "feat: add something",
		},
		{
			name:     "No closing tag",
			output:   "Here it is: <commit_message>feat: add something",
			expected: "feat: add something",
		},
		{
			name:     "Multiple tags (uses last)",
			output:   "<commit_message>fix: previous</commit_message>\n<commit_message>feat: final</commit_message>",
			expected: "feat: final",
		},
		{
			name:     "Empty tags",
			output:   "<commit_message></commit_message>",
			expected: "",
		},
		{
			name:     "No tags",
			output:   "Just some output without tags.",
			expected: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := extractCommitMessage(tt.output)
			if got != tt.expected {
				t.Errorf("extractCommitMessage() = %q, want %q", got, tt.expected)
			}
		})
	}
}
