package runner

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/darkLord19/foglet/internal/git"
	"github.com/darkLord19/foglet/internal/proc"
)

func (r *Runner) commitSessionChanges(ctx context.Context, toolName, workdir, prompt, commitMsg string) (sha, finalMsg string, changed bool, err error) {
	g := git.New(workdir).WithContext(ctx)

	dirty, err := g.IsDirty()
	if err != nil {
		return "", "", false, fmt.Errorf("git status failed: %w", err)
	}
	if !dirty {
		return "", "", false, nil
	}

	if err := g.StageAll(); err != nil {
		return "", "", false, fmt.Errorf("git add failed: %w", err)
	}

	finalMsg = strings.TrimSpace(commitMsg)
	if finalMsg == "" {
		generated, err := r.generateCommitMessage(ctx, toolName, workdir, prompt)
		if isCanceledError(err) {
			return "", "", false, err
		}
		if err != nil || strings.TrimSpace(generated) == "" {
			finalMsg = fallbackCommitMessage(prompt)
		} else {
			finalMsg = generated
		}
	}

	sha, err = g.Commit(finalMsg)
	if err != nil {
		return "", "", false, fmt.Errorf("git commit failed: %w", err)
	}
	return sha, finalMsg, true, nil
}

func (r *Runner) pushBranch(ctx context.Context, workdir, branch string, setUpstream bool) error {
	if err := git.New(workdir).WithContext(ctx).Push(branch, setUpstream); err != nil {
		return fmt.Errorf("git push failed: %w", err)
	}
	return nil
}

func (r *Runner) createDraftPR(ctx context.Context, workdir, baseBranch, branch, prompt, tool, sessionID, customTitle string) (string, error) {
	if r.publisher == nil || !r.publisher.Available() {
		return "", fmt.Errorf("gh CLI not available")
	}
	title := resolvePRTitle(customTitle, prompt)
	body := fmt.Sprintf("Generated by Fog session\n\nSession ID: %s\nAI Tool: %s\n\nPrompt:\n%s",
		sessionID,
		tool,
		strings.TrimSpace(prompt),
	)

	return r.publisher.CreatePR(ctx, workdir, title, body, baseBranch, branch, true)
}

func withOutput(err error, output []byte) error {
	if err == nil {
		return nil
	}
	text := strings.TrimSpace(string(output))
	if text == "" {
		return err
	}
	return fmt.Errorf("%w\n%s", err, text)
}

func isCanceledError(err error) bool {
	return errors.Is(err, proc.ErrCanceled) || errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded)
}

var nonWorktreeNameChar = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

func runWorktreeName(branch, runID string) string {
	branch = nonWorktreeNameChar.ReplaceAllString(strings.TrimSpace(branch), "-")
	branch = strings.Trim(branch, "-._")
	if branch == "" {
		branch = "run"
	}
	if len(branch) > 180 {
		branch = branch[:180]
		branch = strings.Trim(branch, "-._")
		if branch == "" {
			branch = "run"
		}
	}
	suffix := strings.TrimSpace(runID)
	if len(suffix) > 8 {
		suffix = suffix[:8]
	}
	suffix = nonWorktreeNameChar.ReplaceAllString(suffix, "")
	if suffix == "" {
		suffix = "latest"
	}
	return branch + "-" + suffix
}

func fallbackCommitMessage(prompt string) string {
	base := strings.TrimSpace(prompt)
	if base == "" {
		base = "update code"
	}
	return fmt.Sprintf("feat: %s\n\nGenerated by Fog session", truncate(base, 120))
}
